# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guilayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gudrunFormat = QtWidgets.QRadioButton(self.centralwidget)
        self.gudrunFormat.setGeometry(QtCore.QRect(480, 80, 121, 20))
        self.gudrunFormat.setObjectName("gudrunFormat")
        self.pdfgetxFormat = QtWidgets.QRadioButton(self.centralwidget)
        self.pdfgetxFormat.setGeometry(QtCore.QRect(350, 80, 121, 20))
        self.pdfgetxFormat.setChecked(False)
        self.pdfgetxFormat.setObjectName("pdfgetxFormat")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(20, 10, 221, 21))
        self.filename.setObjectName("filename")
        self.bkgfilename = QtWidgets.QLineEdit(self.centralwidget)
        self.bkgfilename.setGeometry(QtCore.QRect(20, 40, 221, 22))
        self.bkgfilename.setObjectName("bkgfilename")
        self.bkgscalebox = QtWidgets.QSpinBox(self.centralwidget)
        self.bkgscalebox.setGeometry(QtCore.QRect(371, 190, 61, 22))
        self.bkgscalebox.setProperty("value", 1)
        self.bkgscalebox.setObjectName("bkgscalebox")
        self.qminbox = QtWidgets.QSpinBox(self.centralwidget)
        self.qminbox.setGeometry(QtCore.QRect(371, 230, 61, 22))
        self.qminbox.setProperty("value", 1)
        self.qminbox.setObjectName("qminbox")
        self.qmaxbox = QtWidgets.QSpinBox(self.centralwidget)
        self.qmaxbox.setGeometry(QtCore.QRect(371, 270, 61, 22))
        self.qmaxbox.setProperty("value", 23)
        self.qmaxbox.setObjectName("qmaxbox")
        self.rpolybox = QtWidgets.QSpinBox(self.centralwidget)
        self.rpolybox.setGeometry(QtCore.QRect(371, 340, 61, 21))
        self.rpolybox.setMaximum(5)
        self.rpolybox.setProperty("value", 1)
        self.rpolybox.setObjectName("rpolybox")
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setGeometry(QtCore.QRect(300, 10, 55, 16))
        self.fileLabel.setObjectName("fileLabel")
        self.bkgFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.bkgFileLabel.setGeometry(QtCore.QRect(300, 40, 101, 31))
        self.bkgFileLabel.setObjectName("bkgFileLabel")
        self.bkgscaleLabel = QtWidgets.QLabel(self.centralwidget)
        self.bkgscaleLabel.setGeometry(QtCore.QRect(450, 190, 121, 16))
        self.bkgscaleLabel.setObjectName("bkgscaleLabel")
        self.rpolyLabel = QtWidgets.QLabel(self.centralwidget)
        self.rpolyLabel.setGeometry(QtCore.QRect(450, 340, 81, 16))
        self.rpolyLabel.setObjectName("rpolyLabel")
        self.QminLabel = QtWidgets.QLabel(self.centralwidget)
        self.QminLabel.setGeometry(QtCore.QRect(450, 230, 71, 16))
        self.QminLabel.setObjectName("QminLabel")
        self.QmaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.QmaxLabel.setGeometry(QtCore.QRect(450, 270, 71, 16))
        self.QmaxLabel.setObjectName("QmaxLabel")
        self.qmaxinstbox = QtWidgets.QSpinBox(self.centralwidget)
        self.qmaxinstbox.setGeometry(QtCore.QRect(371, 310, 61, 21))
        self.qmaxinstbox.setProperty("value", 23)
        self.qmaxinstbox.setObjectName("qmaxinstbox")
        self.qmaxinstLabel = QtWidgets.QLabel(self.centralwidget)
        self.qmaxinstLabel.setGeometry(QtCore.QRect(450, 310, 81, 16))
        self.qmaxinstLabel.setObjectName("qmaxinstLabel")
        self.filelistBox = QtWidgets.QComboBox(self.centralwidget)
        self.filelistBox.setGeometry(QtCore.QRect(20, 150, 201, 22))
        self.filelistBox.setObjectName("filelistBox")
        self.fileListLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileListLabel.setGeometry(QtCore.QRect(230, 150, 55, 16))
        self.fileListLabel.setObjectName("fileListLabel")
        self.compositionBox = QtWidgets.QLineEdit(self.centralwidget)
        self.compositionBox.setGeometry(QtCore.QRect(20, 80, 141, 22))
        self.compositionBox.setObjectName("compositionBox")
        self.compositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.compositionLabel.setGeometry(QtCore.QRect(170, 80, 81, 16))
        self.compositionLabel.setObjectName("compositionLabel")
        self.bkgfilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.bkgfilebutton.setGeometry(QtCore.QRect(250, 40, 41, 28))
        self.bkgfilebutton.setObjectName("bkgfilebutton")
        self.iqcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.iqcheckBox.setGeometry(QtCore.QRect(330, 130, 81, 20))
        self.iqcheckBox.setObjectName("iqcheckBox")
        self.sqCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.sqCheckBox.setGeometry(QtCore.QRect(420, 130, 81, 20))
        self.sqCheckBox.setObjectName("sqCheckBox")
        self.fqCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.fqCheckBox.setGeometry(QtCore.QRect(520, 130, 81, 20))
        self.fqCheckBox.setObjectName("fqCheckBox")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(410, 470, 93, 28))
        self.saveButton.setObjectName("saveButton")
        self.plotLabel = QtWidgets.QLabel(self.centralwidget)
        self.plotLabel.setGeometry(QtCore.QRect(430, 110, 41, 16))
        self.plotLabel.setObjectName("plotLabel")
        self.grCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.grCheckBox.setGeometry(QtCore.QRect(590, 130, 81, 20))
        self.grCheckBox.setObjectName("grCheckBox")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(250, 10, 41, 28))
        self.fileButton.setObjectName("fileButton")
        self.QButton = QtWidgets.QRadioButton(self.centralwidget)
        self.QButton.setGeometry(QtCore.QRect(400, 30, 121, 20))
        self.QButton.setChecked(True)
        self.QButton.setObjectName("QButton")
        self.twothetaButton = QtWidgets.QRadioButton(self.centralwidget)
        self.twothetaButton.setGeometry(QtCore.QRect(470, 30, 121, 20))
        self.twothetaButton.setObjectName("twothetaButton")
        self.wavelengthBox = QtWidgets.QLineEdit(self.centralwidget)
        self.wavelengthBox.setGeometry(QtCore.QRect(20, 110, 141, 22))
        self.wavelengthBox.setObjectName("wavelengthBox")
        self.wavelengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.wavelengthLabel.setGeometry(QtCore.QRect(180, 110, 81, 16))
        self.wavelengthLabel.setObjectName("wavelengthLabel")
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(310, 470, 93, 28))
        self.plotButton.setObjectName("plotButton")
        self.inputFormatLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputFormatLabel.setGeometry(QtCore.QRect(420, 10, 81, 16))
        self.inputFormatLabel.setObjectName("inputFormatLabel")
        self.rminBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rminBox.setGeometry(QtCore.QRect(120, 290, 62, 22))
        self.rminBox.setMinimum(0.01)
        self.rminBox.setMaximum(100.0)
        self.rminBox.setSingleStep(0.1)
        self.rminBox.setProperty("value", 0.5)
        self.rminBox.setObjectName("rminBox")
        self.rmaxBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rmaxBox.setGeometry(QtCore.QRect(120, 330, 62, 22))
        self.rmaxBox.setMinimum(3.0)
        self.rmaxBox.setMaximum(10000.0)
        self.rmaxBox.setProperty("value", 30.0)
        self.rmaxBox.setObjectName("rmaxBox")
        self.rstepBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rstepBox.setGeometry(QtCore.QRect(120, 370, 62, 22))
        self.rstepBox.setDecimals(3)
        self.rstepBox.setMinimum(0.005)
        self.rstepBox.setMaximum(1.0)
        self.rstepBox.setSingleStep(0.01)
        self.rstepBox.setObjectName("rstepBox")
        self.rminLabel = QtWidgets.QLabel(self.centralwidget)
        self.rminLabel.setGeometry(QtCore.QRect(200, 290, 55, 16))
        self.rminLabel.setObjectName("rminLabel")
        self.rmaxLablel = QtWidgets.QLabel(self.centralwidget)
        self.rmaxLablel.setGeometry(QtCore.QRect(200, 330, 55, 16))
        self.rmaxLablel.setObjectName("rmaxLablel")
        self.rstepLabel = QtWidgets.QLabel(self.centralwidget)
        self.rstepLabel.setGeometry(QtCore.QRect(200, 370, 55, 16))
        self.rstepLabel.setObjectName("rstepLabel")
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(220, 180, 111, 28))
        self.removeButton.setObjectName("removeButton")
        self.updatePlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.updatePlotButton.setGeometry(QtCore.QRect(310, 500, 93, 28))
        self.updatePlotButton.setObjectName("updatePlotButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gudrunFormat.setText(_translate("MainWindow", "gudrun format"))
        self.pdfgetxFormat.setText(_translate("MainWindow", "pdfgetx format"))
        self.fileLabel.setText(_translate("MainWindow", "file"))
        self.bkgFileLabel.setText(_translate("MainWindow", "background\n"
"file"))
        self.bkgscaleLabel.setText(_translate("MainWindow", "background scale"))
        self.rpolyLabel.setText(_translate("MainWindow", "rpoly"))
        self.QminLabel.setText(_translate("MainWindow", "Qmin"))
        self.QmaxLabel.setText(_translate("MainWindow", "Qmax"))
        self.qmaxinstLabel.setText(_translate("MainWindow", "Qmax inst"))
        self.fileListLabel.setText(_translate("MainWindow", "File list"))
        self.compositionLabel.setText(_translate("MainWindow", "composition"))
        self.bkgfilebutton.setText(_translate("MainWindow", "file"))
        self.iqcheckBox.setText(_translate("MainWindow", "I(Q)"))
        self.sqCheckBox.setText(_translate("MainWindow", "S(Q)"))
        self.fqCheckBox.setText(_translate("MainWindow", "F(Q)"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.plotLabel.setText(_translate("MainWindow", "Plot"))
        self.grCheckBox.setText(_translate("MainWindow", "G(r)"))
        self.fileButton.setText(_translate("MainWindow", "file"))
        self.fileButton.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.QButton.setText(_translate("MainWindow", "Q"))
        self.twothetaButton.setText(_translate("MainWindow", "2theta"))
        self.wavelengthLabel.setText(_translate("MainWindow", "wavelength"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.inputFormatLabel.setText(_translate("MainWindow", "Input format"))
        self.rminLabel.setText(_translate("MainWindow", "rmin (Å)"))
        self.rmaxLablel.setText(_translate("MainWindow", "rmax (Å)"))
        self.rstepLabel.setText(_translate("MainWindow", "rstep (Å)"))
        self.removeButton.setText(_translate("MainWindow", "remove from list"))
        self.updatePlotButton.setText(_translate("MainWindow", "update plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))

